/**
 * Mock data for the Civic Connect app
 * This file contains sample data for development and testing purposes
 */

// Sample issue categories
export const issueCategories = [
  { id: '1', name: 'Roads', icon: 'road' },
  { id: '2', name: 'Lighting', icon: 'lightbulb-outline' },
  { id: '3', name: 'Sanitation', icon: 'trash-can-outline' },
  { id: '4', name: 'Parks', icon: 'tree' },
  { id: '5', name: 'Vandalism', icon: 'spray' },
  { id: '6', name: 'Water', icon: 'water' },
  { id: '7', name: 'Electricity', icon: 'flash' },
  { id: '8', name: 'Public Safety', icon: 'shield' },
  { id: '9', name: 'Other', icon: 'dots-horizontal' },
];

// Sample issues data
export const issuesData = [
  {
    id: '1',
    title: 'Pothole on Main Street',
    description: 'Large pothole causing traffic hazards near the intersection with Oak Avenue. Multiple vehicles have reported damage.',
    category: 'Roads',
    location: '123 Main St',
    coordinates: { latitude: 37.78825, longitude: -122.4324 },
    reportedBy: 'John Doe',
    reportedDate: '2023-06-15',
    status: 'Pending',
    priority: 'High',
    images: [],
    updates: [
      { date: '2023-06-15', content: 'Issue reported', author: 'John Doe' },
      { date: '2023-06-16', content: 'Scheduled for inspection', author: 'Admin' },
    ],
  },
  {
    id: '2',
    title: 'Broken Street Light',
    description: 'Street light not working at night, creating a safety hazard for pedestrians and drivers.',
    category: 'Lighting',
    location: '456 Oak Ave',
    coordinates: { latitude: 37.78925, longitude: -122.4344 },
    reportedBy: 'Jane Smith',
    reportedDate: '2023-06-14',
    status: 'In Progress',
    priority: 'Medium',
    images: [],
    updates: [
      { date: '2023-06-14', content: 'Issue reported', author: 'Jane Smith' },
      { date: '2023-06-15', content: 'Technician assigned', author: 'Admin' },
      { date: '2023-06-17', content: 'Parts ordered', author: 'Technician' },
    ],
  },
  {
    id: '3',
    title: 'Overflowing Trash Bin',
    description: 'Trash bin overflowing in public park, attracting pests and creating unpleasant odors.',
    category: 'Sanitation',
    location: 'Central Park',
    coordinates: { latitude: 37.78725, longitude: -122.4314 },
    reportedBy: 'Mike Johnson',
    reportedDate: '2023-06-13',
    status: 'Resolved',
    priority: 'Low',
    images: [],
    updates: [
      { date: '2023-06-13', content: 'Issue reported', author: 'Mike Johnson' },
      { date: '2023-06-14', content: 'Cleaning crew assigned', author: 'Admin' },
      { date: '2023-06-15', content: 'Trash removed and bin emptied', author: 'Cleaning Crew' },
      { date: '2023-06-15', content: 'Issue marked as resolved', author: 'Admin' },
    ],
  },
  {
    id: '4',
    title: 'Graffiti on Public Building',
    description: 'Vandalism on community center wall, offensive content needs to be removed.',
    category: 'Vandalism',
    location: 'Community Center',
    coordinates: { latitude: 37.78625, longitude: -122.4334 },
    reportedBy: 'Sarah Williams',
    reportedDate: '2023-06-12',
    status: 'In Progress',
    priority: 'Medium',
    images: [],
    updates: [
      { date: '2023-06-12', content: 'Issue reported', author: 'Sarah Williams' },
      { date: '2023-06-13', content: 'Cleaning team scheduled', author: 'Admin' },
      { date: '2023-06-16', content: 'Special cleaning supplies ordered', author: 'Maintenance' },
    ],
  },
  {
    id: '5',
    title: 'Fallen Tree Blocking Sidewalk',
    description: 'Tree fell after storm and blocks pedestrian path completely. Pedestrians are forced to walk on the road.',
    category: 'Parks',
    location: '789 Elm St',
    coordinates: { latitude: 37.78525, longitude: -122.4354 },
    reportedBy: 'David Brown',
    reportedDate: '2023-06-11',
    status: 'Pending',
    priority: 'High',
    images: [],
    updates: [
      { date: '2023-06-11', content: 'Issue reported', author: 'David Brown' },
      { date: '2023-06-12', content: 'Assessment scheduled', author: 'Admin' },
    ],
  },
  {
    id: '6',
    title: 'Water Leak from Fire Hydrant',
    description: 'Fire hydrant leaking water onto the street, causing water waste and potential road damage.',
    category: 'Water',
    location: '321 Pine St',
    coordinates: { latitude: 37.78425, longitude: -122.4364 },
    reportedBy: 'Emily Chen',
    reportedDate: '2023-06-10',
    status: 'Resolved',
    priority: 'High',
    images: [],
    updates: [
      { date: '2023-06-10', content: 'Issue reported', author: 'Emily Chen' },
      { date: '2023-06-10', content: 'Emergency team dispatched', author: 'Admin' },
      { date: '2023-06-10', content: 'Leak fixed', author: 'Water Department' },
      { date: '2023-06-11', content: 'Issue marked as resolved', author: 'Admin' },
    ],
  },
  {
    id: '7',
    title: 'Damaged Playground Equipment',
    description: 'Swing set in city park has broken chains, creating a safety hazard for children.',
    category: 'Parks',
    location: 'City Park',
    coordinates: { latitude: 37.78325, longitude: -122.4374 },
    reportedBy: 'Robert Wilson',
    reportedDate: '2023-06-09',
    status: 'In Progress',
    priority: 'Medium',
    images: [],
    updates: [
      { date: '2023-06-09', content: 'Issue reported', author: 'Robert Wilson' },
      { date: '2023-06-11', content: 'Inspection completed', author: 'Parks Department' },
      { date: '2023-06-14', content: 'Replacement parts ordered', author: 'Maintenance' },
    ],
  },
  {
    id: '8',
    title: 'Illegal Dumping',
    description: 'Someone has dumped construction waste on vacant lot, creating an eyesore and potential health hazard.',
    category: 'Sanitation',
    location: '555 Maple Ave',
    coordinates: { latitude: 37.78225, longitude: -122.4384 },
    reportedBy: 'Lisa Taylor',
    reportedDate: '2023-06-08',
    status: 'Pending',
    priority: 'Medium',
    images: [],
    updates: [
      { date: '2023-06-08', content: 'Issue reported', author: 'Lisa Taylor' },
      { date: '2023-06-10', content: 'Investigation scheduled', author: 'Admin' },
    ],
  },
];

// Sample user data
export const userData = {
  citizen: {
    id: 'citizen1',
    name: 'John Citizen',
    email: 'john@example.com',
    phone: '(555) 123-4567',
    address: '123 Main St, Anytown, USA',
    joinDate: '2023-01-15',
    reportedIssues: 8,
    resolvedIssues: 5,
    pendingIssues: 3,
  },
  admin: {
    id: 'admin1',
    name: 'Admin User',
    email: 'admin@civicconnect.gov',
    phone: '(555) 987-6543',
    department: 'Public Works',
    role: 'Department Manager',
    joinDate: '2022-06-01',
    issuesManaged: 156,
    resolvedIssues: 79,
    pendingIssues: 42,
  },
};

// Sample analytics data
export const analyticsData = {
  issuesByStatus: [
    { status: 'Resolved', count: 79, percentage: 50 },
    { status: 'Pending', count: 42, percentage: 30 },
    { status: 'In Progress', count: 35, percentage: 20 },
  ],
  issuesByCategory: [
    { category: 'Roads', count: 45 },
    { category: 'Lighting', count: 32 },
    { category: 'Sanitation', count: 28 },
    { category: 'Parks', count: 21 },
    { category: 'Vandalism', count: 15 },
    { category: 'Other', count: 15 },
  ],
  issuesByMonth: [
    { month: 'Jan', count: 12 },
    { month: 'Feb', count: 15 },
    { month: 'Mar', count: 18 },
    { month: 'Apr', count: 22 },
    { month: 'May', count: 28 },
    { month: 'Jun', count: 32 },
  ],
  keyStats: {
    averageResolutionTime: '3.2 days',
    issuesReported: 156,
    resolutionRate: '78%',
    citizenEngagement: '42%',
    mostActiveArea: 'Downtown',
    topIssueCategory: 'Roads',
  },
};